apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: teste2
  labels:
    app: teste
spec:
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: teste
        image: eu.gcr.io/xpectraltest/teste:v2
        ports:
        - containerPort: 8080
